# in _config.yml
title: "Introduction to Scientific Machine Learning (Lecture Book)"
execute:
  execute_notebooks: "off"
author: "Ilias Bilionis (ibilion[at]purdue.edu)"
repository:
  url: "https://github.com/PredictiveScienceLab/data-analytics/lecturebook"
launch_buttons:
  notebook_interface: "jupyterlab"
  colab_url: "https://colab.research.google.com"
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year